import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
// import the library
import { library } from '@fortawesome/fontawesome-svg-core';

// import your icons
// import { faMoneyBill } from '@fortawesome/pro-solid-svg-icons';
import { faCode, faSmog, faBolt, faRobot, faHighlighter  , faPen , faLock } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Roboto, Lobster, Arimo, Pacifico, Karla } from 'next/font/google'
const karla = Karla({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
});

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [reply, setReply] = useState("")
  const [checker, setChecker] = useState(false)
  const [intro1, setIntro1] = useState(true)
  const [intro2, setIntro2] = useState(true)
  const [loader, setloader] = useState(false)
  const [question, setQuestion] = useState("")
  const findAndReplace = (inputString, wordToFind, replacementWord) => {
    const regex = new RegExp(`\\b${wordToFind}\\b`, 'gi');
    return inputString.replace(regex, replacementWord);
  }
  const getMessage = async () => {
    setloader(true)
    setChecker(false)
    setIntro1(false)
    setIntro2(false)
    const options = {
      method: "POST",
      body: JSON.stringify({

        message: "hello how are you?",

      }),
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer YOUR_KEY_HERE`, // Replace YOUR_API_KEY_HERE with your actual OpenAI API key
      },
    }
    try {
      const response = await axios.post(`http://localhost:5000/completion?asked=${question}`, options,)
      // const data = response.json()
      console.log(response.data);
      const inputString = response.data;
      const wordToFind = "As an AI language model";
      const replacementWord = "As a Cyborg Solution's AI language model";
      const outputString = findAndReplace(inputString, wordToFind, replacementWord);
      setReply(outputString)
      setChecker(true)
      setloader(false)
    } catch (error) {
      console.log("THE ERROR", error);
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainImage}>

        <h1 className={karla.className} style={{ color: "white", textAlign: "center" , fontSize:"50px", }}>The Cyborg Convenience Bot</h1>
        
        {intro1 && <>
          <div className={`container ${styles.infoContainer}`}><div className={` row ${styles.x}`}>
            <div className={` col-md-4 ${styles.info1}`}> <FontAwesomeIcon icon={faRobot} className={styles.icon} style={{ color: "skyblue" }} /><h3>Why Cyborg?</h3>

<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginBottom: "5px", borderRadius: "3px" }}><p style={{ paddingBottom: "1px"  , fontSize:"17px"}}>Stay ahead of the curve with real-time post-2021 updates.</p><div className='col-12'></div></div>
<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p style={{ fontSize:"17px"}}>ake informed decisions based on the latest global events..</p><div className='col-12'></div></div>
<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p style={{ fontSize:"17px"}}>Does not provide illogical or biased results.</p><div className='col-12'></div></div></div>
            <div className={` col-md-4 ${styles.info1}`}>
            <FontAwesomeIcon icon={faSmog} className={styles.icon} style={{ color: "red" }} /><h3>Limitations</h3>

<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginBottom: "5px", borderRadius: "3px" }}><p style={{ paddingBottom: "1px" , fontSize:"17px" }}>Limited knowledge of world and events after 2021</p></div>
<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p style={{ fontSize:"17px"}}>Don't let outdated information hold you back—gain future insights.</p></div>
<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p style={{ fontSize:"17px"}}>Access a comprehensive AI model for a deeper understanding.</p></div>
            </div>
            
            <div className={` col-md-4 d-none d-md-block ${styles.info1}`}>
            <FontAwesomeIcon icon={faLock} className={styles.icon} style={{ color: "green", marginTop:"-3px"}} /><h3>Potential</h3>

<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginBottom: "5px", borderRadius: "3px" }}><p style={{ paddingBottom: "1px" , fontSize:"17px" }}>Affordable rates for accessing cutting-edge post-2021 intelligence.</p><div className='col-12'></div></div>
<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p style={{ fontSize:"17px"}}>Get value for your investment with up-to-date knowledge.</p><div className='col-12'></div></div>
<div className='row' style={{ backgroundColor: "white", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p style={{ fontSize:"17px"}}>Experience the power of post-2021 insights without breaking the bank.</p><div className='col-12'></div></div>
            </div>

            </div>

          </div>
        </>}
{/* 
        {intro2 && <>
          <div className={`container ${styles.infoContainer}`}><div className={` row ${styles.x}`}>
            <div className={` col-5 col-md-2 ${styles.info1}`} style={{ position: "fixed", bottom: "110px" }}>
              <FontAwesomeIcon icon={faSmog} className={styles.icon} style={{ color: "red" }} /><h3>Limitations</h3>

              <div className='row' style={{ backgroundColor: "white", opacity: "01", width: "97%", margin: "auto", marginTop: "5px", marginBottom: "5px", borderRadius: "3px" }}><p style={{ paddingBottom: "1px" }}>Limited knowledge of world and events after 2021</p><div className='col-12'></div></div>
              <div className='row' style={{ backgroundColor: "white", opacity: "0.8", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p>May occasionally produce harmful instructions or biased content.</p><div className='col-12'></div></div>
              <div className='row' style={{ backgroundColor: "white", opacity: "0.5", width: "97%", margin: "auto", marginTop: "5px", marginTop: "5px", borderRadius: "3px" }}><p>May occasionally generate incorrect information</p><div className='col-12'></div></div>
            </div>
            <div className={` col-5 ${styles.x}`}>
            </div></div>

          </div>
        </>} */}

        {/* Loader */}

        {loader && <><div className={`container`} style={{marginTop:"150px"}}><div className={`row`}>
          <div className={`col-4`}></div>
          <div className={`col-4`}>  <div className={styles.five}>
            <div className={styles.left}></div>
            <div className={styles.left}></div>
            <div className={styles.left}></div>
            <div className={styles.left}></div>
            <div className={styles.tree}></div>
            <div className={styles.thumbs}></div>
          </div></div>
          <div className={`col-4`}></div>
        </div></div>


        </>}
        {/* answer card */}
        {checker && <><div class={`overflow-auto ${styles.scroller}`} >
          <div className={`container ${styles.mydiv}`}><div className={`row`}>
            <div className={`col-12 `}><p style={{ color: "white" ,padding:"20px"}}>{reply}</p></div></div></div>
        </div></>}


        <div className={`container ${styles.bottomBar} `}><div className={`row`}>
          <div className={`col-3 col-md-4 `}></div> <div className={`col-7 col-md-6 `}> <input className={styles.question} type='text' placeholder='Talk to the AI' onChange={(e) => setQuestion(e.target.value)} /><p className={styles.info}>Free Research Preview. Cyborg ChatBot may produce inaccurate information about people, places, or facts.
          </p></div><div className={`col-1`}><FontAwesomeIcon onClick={getMessage} icon={faPen} className={styles.icon} />
          </div><div className={`col-3`}></div>

        </div>

        </div>

        {/* <div  className={`container ${styles.bottomBar} `}> <div className={`row`}></div></div> */}
        {/* loader */}


      </main>
    </>
  )
}
